HydroServerTools/Controllers/ViewDataController.cs
using HydroServerTools.Helper;
using HydroServerTools.Models;
using HydroserverToolsBusinessObjects;
using HydroServerToolsRepository.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HydroServerTools.Controllers
{
    [Authorize]
    public class ViewDataController : Controller
    {
        //
        // GET: /View/
        public ActionResult Index()
        {
            return View();
        }
        //"Sites", "Variables", "OffsetTypes", "ISOMetadata", "Sources", "Methods", "LabMethods", "Samples", "Qualifiers", "QualityControlLevels", "DataValues", "GroupDescriptions", "Groups", "DerivedFrom", "Categories"};

        //public ActionResult ViewSites()
        //{

        //    string connectionName = Utils.GetConnectionNameByUserEmail(HttpContext.User.Identity.Name.ToString());
            
        //    var entityConnectionString = Utils.GetDBConnectionStringByName(connectionName);
                        
        //    var sitesRepository = new SitesRepository();

        //    return View(sitesRepository.GetAll(entityConnectionString));
          
        //}
        //public ActionResult ViewVariables()
        //{
            
        //    string connectionName = Utils.GetConnectionNameByUserEmail(HttpContext.User.Identity.Name.ToString());
           
        //    var entityConnectionString = Utils.GetDBConnectionStringByName(connectionName);

        //    var variablesRepository = new VariablesRepository();

        //    return View(variablesRepository.GetAll(entityConnectionString));
            
        //}

        public ActionResult ViewTableData(string identifier)
        {
           

            string connectionName = Utils.GetConnectionNameByUserEmail(HttpContext.User.Identity.Name.ToString());

            var entityConnectionString = Utils.GetDBConnectionStringByName(connectionName);

            if (String.IsNullOrEmpty(entityConnectionString)) { ViewBag.Message = Ressources.HYDROSERVER_USERLOOKUP_FAILED; return View("Error"); }


            if (identifier.ToLower() == "sites") { var repo = new SitesRepository(); return View("ViewSites", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "variables") {var  repo = new VariablesRepository(); return View("ViewVariables", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "offsettypes") { var repo = new OffsetTypesRepository(); return View("ViewOffsetTypes", repo.GetAll(entityConnectionString)); };           
            if (identifier.ToLower() == "isometadata") { var repo = new ISOMetadataRepository(); return View("ViewISOMetadata", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "sources") { var repo = new SourcesRepository(); return View("ViewSources", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "methods") { var repo = new MethodsRepository(); return View("ViewMethods", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "labmethods") { var repo = new LabMethodsRepository(); return View("ViewLabMethods", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "samples") { var repo = new SamplesRepository(); return View("ViewSamples", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "qualifiers") { var repo = new QualifiersRepository(); return View("ViewQualifiers", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "qualitycontrollevels") { var repo = new QualityControlLevelsRepository(); return View("ViewQualityControlLevels", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "datavalues") { var repo = new DataValuesRepository(); return View("ViewDataValues", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "groupdescriptions") { var repo = new GroupDescriptionsRepository(); return View("ViewGroupDescriptions", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "groups") { var repo = new GroupsRepository(); return View("ViewGroups", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "derivedfrom") { var repo = new DerivedFromRepository(); return View("ViewDerivedFrom", repo.GetAll(entityConnectionString)); };
            if (identifier.ToLower() == "categories") { var repo = new CategoriesRepository(); return View("ViewCategories", repo.GetAll(entityConnectionString)); };



            return View();
        }

	}
}

HydroServerTools/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HydroServerTools</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="container">
        <div class="row">
            <img src="~/Images/Hydroserver/HydroserverLogo.png" class="center img-thumbnail" style="border:0px; vertical-align:top"/>
        </div>
    </div>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header ">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                  
        </div>
            <div class="navbar-collapse collapse ">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Datatable1", "Datatable1", "Home")</li>
                    <li>@Html.ActionLink("Datatable2", "Datatable2", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">View Data<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("View Sites", "ViewTableData", "ViewData", new { identifier = "Sites" }, null)</li>
                            <li>@Html.ActionLink("View Variables", "ViewTableData", "ViewData", new { identifier = "Variables" }, null)</li>                            
                            <li>@Html.ActionLink("View OffsetTypes", "ViewTableData", "ViewData", new { identifier = "OffsetTypes" }, null)</li>
                            <li>@Html.ActionLink("View ISOMetadata", "ViewTableData", "ViewData", new { identifier = "ISOMetadata" }, null)</li>
                            <li>@Html.ActionLink("View Sources", "ViewTableData", "ViewData", new { identifier = "Sources" }, null)</li>
                            <li>@Html.ActionLink("View Methods", "ViewTableData", "ViewData", new { identifier = "Methods" }, null)</li>
                            <li>@Html.ActionLink("View LabMethods", "ViewTableData", "ViewData", new { identifier = "LabMethods" }, null)</li>
                            <li>@Html.ActionLink("View Samples", "ViewTableData", "ViewData", new { identifier = "Samples" }, null)</li>
                            <li>@Html.ActionLink("View Qualifiers", "ViewTableData", "ViewData", new { identifier = "Qualifiers" }, null)</li>
                            <li>@Html.ActionLink("View QualityControlLevels", "ViewTableData", "ViewData", new { identifier = "QualityControlLevels" }, null)</li>
                            <li>@Html.ActionLink("View DataValues", "ViewTableData", "ViewData", new { identifier = "DataValues" }, null)</li>
                            <li>@Html.ActionLink("View GroupDescriptions", "ViewTableData", "ViewData", new { identifier = "GroupDescriptions" }, null)</li>
                            <li>@Html.ActionLink("View Groups", "ViewTableData", "ViewData", new { identifier = "Groups" }, null)</li>
                            <li>@Html.ActionLink("View DerivedFrom", "ViewTableData", "ViewData", new { identifier = "DerivedFrom" }, null)</li>
                            <li>@Html.ActionLink("View Categories", "ViewTableData", "ViewData", new { identifier = "Categories" }, null)</li>

                            <li><a href="#">View OffsetTypes</a></li>
                            <li class="divider"></li>
                            <li><a href="#">View DateTyp CV</a></li>
                        </ul>
                    </li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
  
    <div class="container body-content">
      
          @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - &copy; CUAHSI </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
  
</body>
</html> 