HydroServerTools/Models/DataValuesViewModel.cs
using HydroserverToolsBusinessObjects.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HydroServerTools.Models
{
    public class DataValuesViewModel
    {

        public List<DataValuesModel> listOfIncorrectRecords { get; set; }
        public List<DataValuesModel> listOfCorrectRecords { get; set; }
        public List<DataValuesModel> listOfDuplicateRecords { get; set; }
        public List<DataValuesModel> listOfEditedRecords { get; set; }
         
    }
}

HydroServerTools/Models/MethodsViewModel.cs
using HydroserverToolsBusinessObjects.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HydroServerTools.Models
{
    public class SitesViewModel
    {

        public List<SiteModel> listOfIncorrectRecords { get; set; }
        public List<SiteModel> listOfCorrectRecords { get; set; }
        public List<SiteModel> listOfDuplicateRecords { get; set; }
        public List<SiteModel> listOfEditedRecords { get; set; }
         
    }
}

HydroServerTools/Models/SitesViewModel.cs
using HydroserverToolsBusinessObjects.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HydroServerTools.Models
{
    public class VariablesViewModel
    {

        public List<VariablesModel> listOfIncorrectRecords { get; set; }
        public List<VariablesModel> listOfCorrectRecords { get; set; }
        public List<VariablesModel> listOfDuplicateRecords { get; set; }
        public List<VariablesModel> listOfEditedRecords { get; set; }
         
    }
}

HydroServerTools/Models/SourcesViewModel.cs
using HydroserverToolsBusinessObjects.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HydroServerTools.Models
{
    public class SourcesViewModel
    {

        public List<SourcesModel> listOfIncorrectRecords { get; set; }
        public List<SourcesModel> listOfCorrectRecords { get; set; }
        public List<SourcesModel> listOfDuplicateRecords { get; set; }
        public List<SourcesModel> listOfEditedRecords { get; set; }
         
    }
}

HydroServerTools/Models/VariablesViewModel.cs
using HydroserverToolsBusinessObjects.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HydroServerTools.Models
{
    public class MethodsViewModel
    {
        public List<MethodModel> listOfIncorrectRecords { get; set; }
        public List<MethodModel> listOfCorrectRecords { get; set; }
        public List<MethodModel> listOfDuplicateRecords { get; set; }
        public List<MethodModel> listOfEditedRecords { get; set; }
         
    }
}

HydroServerTools/Controllers/CSVUploadController.cs
using CsvHelper;
using HydroServerTools.Helper;
using HydroServerTools.Models;
using HydroserverToolsBusinessObjects;
using HydroserverToolsBusinessObjects.Models;
using HydroServerToolsRepository.Repository;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core;
using System.Data.Entity.Core.EntityClient;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace HydroServerTools.Controllers
{
    [Authorize]
    public class CSVUploadController : Controller
    {

         //
        // GET: /CSVUpload/
        public ActionResult Index(ExternalLoginConfirmationViewModel model)
        {
            
            return View();
        }
        public ActionResult TestConnection(ConnectionModel model)
        {

            if (ModelState.IsValid)
            {

                var connectionString = Helper.Utils.BuildEFConnnectionString(model);

                //Get Connection
                var conn = new EntityConnection(connectionString);
                                
                //Initialize vars
                string message = string.Empty;
                string status = "failed";
                //test connectionstring
                try
                {
                    conn.Open();
                    message = HISRessources.CONNECTION_SUCCESS;
                    status = "success";
                    conn.Close();
                }

                catch (EntityException ex)
                {
                    if (ex.InnerException.Message.StartsWith("A network-related"))
                        message = HISRessources.CONNECTION_FAILED_SERVERNAME;
                    else if (ex.InnerException.Message.StartsWith("Cannot open database"))
                        message = HISRessources.CONNECTION_FAILED_DATASOURCENAME;
                    else
                    {
                        message = HISRessources.CONNECTION_FAILED_LOGIN;
                    }

                }
                catch (Exception ex)
                {
                    model.Message = "An error occured. Please notify the technical team.";
                }
                finally
                {
                    model.Message = message;
                    model.Status = status;
                    conn.Close();
                      
                }


                
            }
            //ViewBag.Message = "tes";

            return View("Index", model);
        }

        public ActionResult Upload()
        {
            return View("Upload");
        }

        public ActionResult Sites()
        {            
            return View("Sites");
        }
        public ActionResult Variables()
        {
            return View("Variables");
        }
        public ActionResult OffsetTypes()
        { 
            return View ("OffsetTypes");
        }
         public ActionResult ISOMetadata() 
         { 
             return View ("ISOMetadata");
         }
         public ActionResult Sources() 
         { 
             return View ("Sources");
         }
         public ActionResult Methods() 
         { 
             return View("Methods");
         }
         public ActionResult LabMethods() 
         { 
             return View("LabMethods");
         }
         public ActionResult Samples() 
         { 
             return View("Samples");
         }
         public ActionResult Qualifiers() 
         { 
             return View("Qualifiers");
         }
         public ActionResult QualityControlLevels() 
         { 
             return View("QualityControlLevels");
         }
         public ActionResult DataValues() 
         { 
             return View("DataValues");
         }
         public ActionResult GroupDescriptions() 
         { 
             return View("GroupDescriptions");
         }
         public ActionResult Groups() 
         { 
             return View("Groups");
         }
         public ActionResult DerivedFrom() 
         { 
             return View("DerivedFrom");
         }
         public ActionResult Categories() 
         { 
             return View("Categories");
         }
        public ContentResult _Breadcrumb(string name)
        {

            string[] vars = new string[14] { "Sites", "Variables", "OffsetTypes", "Sources", "Methods", "LabMethods", "Samples", "Qualifiers", "QualityControlLevels", "DataValues", "GroupDescriptions", "Groups", "DerivedFrom", "Categories" };//"ISOMetadata",
          
            StringBuilder html = new StringBuilder();
            html.Append("<div>");
            html.Append("<ol class='breadcrumb h6'>");
            foreach (var item in vars)
            {
                if (name.ToLower() == item.ToLower()) html.Append("<li class='active h4'><strong>" + item + "</strong></li>");

                else
                {
                    
                    html.Append("<li><a href ='");
                    html.Append("/CSVUpload/");
                    html.Append(item);
                    html.Append("' >");
                    html.Append(item);
                    html.Append("</a></li>");
                }
            }
            html.Append("</ol>");
            html.Append("</div>");
            return Content(html.ToString());
        }

        [HttpPost]
        public ActionResult Import(HttpPostedFileBase file, FormCollection collection)//
        {
            //string userName = HttpContext.User.Identity.Name;//  "martin.seul@yahoo.com";
            //var Db = new ApplicationDbContext();
            //var userEmail = Db.Users.First(u => u.UserName == userName).UserEmail;
            
            //Get Connection string
            var connectionName = Utils.GetConnectionNameByUserEmail(HttpContext.User.Identity.Name);
            var entityConnectionString = Utils.GetDBConnectionStringByName(connectionName);
            string viewName = collection["viewname"];
            if (String.IsNullOrEmpty(connectionName))
            { 
                ModelState.AddModelError(String.Empty, Ressources.HYDROSERVER_USERLOOKUP_FAILED);
                return View(viewName);
            }
            //Object T;
            try
            {
                #region Sites
                //  
                if (viewName.ToLower() == "sites")
                {
                    List<SiteModel> values = null;

                    var siteViewModel = new SitesViewModel();
                    var listOfIncorrectRecords = new List<SiteModel>();
                    var listOfCorrectRecords = new List<SiteModel>();
                    var listOfDuplicateRecords = new List<SiteModel>();
                    var listOfEditedRecords = new List<SiteModel>();

                    // Verify that the user selected a file
                    if (file != null && file.ContentLength > 0)
                    {

                        values = parseCSV<SiteModel>(file);
                    }


                    if (values != null)
                    {
                        var sitesRepository = new SitesRepository();

                        sitesRepository.AddSites(values, entityConnectionString, out listOfIncorrectRecords, out listOfCorrectRecords, out listOfDuplicateRecords, out listOfEditedRecords);
                    }

                    //var table = Utils.GetDatatableForModel<SiteModel>(sites[0]);

                    @ViewBag.numberOfCorrectRecords = listOfCorrectRecords.Count();
                    @ViewBag.numberOfDuplicateRecords = listOfDuplicateRecords.Count();
                    // redirect back to the index action to show the form once again

                    siteViewModel.listOfCorrectRecords = listOfCorrectRecords;
                    siteViewModel.listOfIncorrectRecords = listOfIncorrectRecords;
                    siteViewModel.listOfEditedRecords = listOfEditedRecords;
                    siteViewModel.listOfDuplicateRecords = listOfDuplicateRecords;

                    return View(viewName, siteViewModel);
                } 
                #endregion
                
                #region Variables
                if (viewName.ToLower() == "variables")
                {
                    List<VariablesModel> values = null;

                    var variablesViewModel = new VariablesViewModel();
                    var listOfIncorrectRecords = new List<VariablesModel>();
                    var listOfCorrectRecords = new List<VariablesModel>();
                    var listOfDuplicateRecords = new List<VariablesModel>();
                    var listOfEditedRecords = new List<VariablesModel>();
                    // Verify that the user selected a file
                    if (file != null && file.ContentLength > 0)
                    {

                        values = parseCSV<VariablesModel>(file);
                    }


                    if (values != null)
                    {
                        var repository = new VariablesRepository();

                        repository.AddVariables(values, entityConnectionString, out listOfIncorrectRecords, out listOfCorrectRecords, out listOfDuplicateRecords, out listOfEditedRecords);
                    }

                    //var table = Utils.GetDatatableForModel<SiteModel>(sites[0]);

                    @ViewBag.numberOfCorrectRecords = listOfCorrectRecords.Count();
                    @ViewBag.numberOfDuplicateRecords = listOfDuplicateRecords.Count();

                    variablesViewModel.listOfCorrectRecords = listOfCorrectRecords;
                    variablesViewModel.listOfIncorrectRecords = listOfIncorrectRecords;
                    variablesViewModel.listOfEditedRecords = listOfEditedRecords;
                    variablesViewModel.listOfDuplicateRecords = listOfDuplicateRecords;

HydroServerTools/Views/CSVUpload/DataValues.cshtml
@model HydroServerTools.Models.DataValuesViewModel

@{
    ViewBag.Title = "DataValues";
    ViewBag.Name = "DataValues";
}
@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/demo_table.css" rel="stylesheet" />
    @*<link href="~/Content/DataTables-1.9.4/media/css/demo_table_jui.css" rel="stylesheet" />*@
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools.css" rel="stylesheet" />
    @*<link href="~/Content/DataTables-1.9.4/media/css/jquery.dataTables_themeroller.css" rel="stylesheet" />*@
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
}
@Html.Action("_Breadcrumb", "CSVUpload", new { name = ViewBag.Name })
@if (Model == null)
{
    Html.RenderPartial("_UploadForm");
}


@if (Model != null)
{

    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Added</a></li>
            <li><a href="#tabs-2">Rejected</a></li>
            <li><a href="#tabs-3">Edited</a></li>
            <li><a href="#tabs-4">Duplicate</a></li>
        </ul>

        @*<div class="panel panel-info">
                <span class="green">You successfully added @ViewBag.numberOfCorrectRecords new record(s) to the @ViewBag.Name table. @ViewBag.numberOfDuplicateRecords record(s) were duplicates.</span>
            </div>*@
        <div id="tabs-1">
            @if (Model.listOfCorrectRecords.Count() > 0)
            {
                { Html.RenderPartial("_UploadDataBaseTable", Model.listOfCorrectRecords); }

            }
        </div>
        <div id="tabs-2">
            @if (Model.listOfIncorrectRecords.Count() > 0)
            {
                @*<h4>List of rejected  @ViewBag.Name please review and re-upload</h4>*@
                { Html.RenderPartial("_UploadDataBaseTable", Model.listOfIncorrectRecords); }
            }
        </div>
        <div id="tabs-3">
            @if (Model.listOfEditedRecords.Count() > 0)
            {

                @*          <h4>List of edited  @ViewBag.Name please review and re-upload</h4>*@
                { Html.RenderPartial("_UploadDataBaseTable", Model.listOfEditedRecords); }

            }

        </div>
        <div id="tabs-4">
            @if (Model.listOfDuplicateRecords.Count() > 0)
            {

                @*             <h4>List of duplicate  @ViewBag.Name please review and re-upload</h4>*@
                { Html.RenderPartial("_UploadDataBaseTable", Model.listOfDuplicateRecords); }
            }

        </div>
    </div>
}

@section scripts
{
    <script type='text/javascript' src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script type='text/javascript' src="http://datatables.net/release-datatables/media/js/jquery.dataTables.js"></script>

    <script src="~/Scripts/DataTables-1.9.4/extras/TableTools/media/js/TableTools.js"></script>
    <script src="~/Scripts/DataTables-1.9.4/extras/TableTools/media/js/ZeroClipboard.js"></script>


    <script src="~/Scripts/custom/CSVUploadHelper.js"></script>
    <script>

    </script>
}

HydroServerTools/Views/CSVUpload/DerivedFrom.cshtml
@model IEnumerable<HydroserverToolsBusinessObjects.Models.DerivedFromModel>
@{
    ViewBag.Title = "DerivedFrom";
    ViewBag.Name = "DerivedFrom";
}


@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/jquery.dataTables_themeroller.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
}
@Html.Action("_Breadcrumb", "CSVUpload", new { name = ViewBag.Name })
@if (Model == null)
{
    Html.RenderPartial("_UploadForm");
}
@if (Model != null)
{
    <div class="panel panel-info">
        <span class="red">You successfully added @ViewBag.numberOfCorrectRecords new record(s) to the @ViewBag.Name table. @ViewBag.numberOfDuplicateRecords record(s) were duplicates.</span>
    </div>
    if (Model.Count() > 0)
    {
        <div class="display" id="DBTable">
            <h4>List of rejected  @ViewBag.Name please review and re-upload</h4>
            @{Html.RenderPartial("_DataBaseTable", Model);}
        </div>
    }
}
@section scripts
{
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/DataTables-1.9.4/extras/TableTools/media/js/TableTools.min.js"></script>
    <script src="~/Scripts/custom/ViewDataHelper.js"></script>
}

HydroServerTools/Views/CSVUpload/GroupDescriptions.cshtml
@model IEnumerable<HydroserverToolsBusinessObjects.Models.GroupDescriptionModel>
@{
    ViewBag.Title = "GroupDescriptions";
    ViewBag.Name = "GroupDescriptions";
}


@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/jquery.dataTables_themeroller.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
}
@Html.Action("_Breadcrumb", "CSVUpload", new { name = ViewBag.Name })
@if (Model == null)
{
    Html.RenderPartial("_UploadForm");
}
@if (Model != null)
{
    <div class="panel panel-info">
        <span class="red">You successfully added @ViewBag.numberOfCorrectRecords new record(s) to the @ViewBag.Name table. @ViewBag.numberOfDuplicateRecords record(s) were duplicates.</span>
    </div>
    if (Model.Count() > 0)
    {
        <div class="display" id="DBTable">
            <h4>List of rejected  @ViewBag.Name please review and re-upload</h4>
            @{Html.RenderPartial("_DataBaseTable", Model);}
        </div>
    }
}
@section scripts
{
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/DataTables-1.9.4/extras/TableTools/media/js/TableTools.min.js"></script>
    <script src="~/Scripts/custom/ViewDataHelper.js"></script>
}

HydroServerTools/Views/CSVUpload/Groups.cshtml
@model IEnumerable<HydroserverToolsBusinessObjects.Models.GroupsModel>
@{
    ViewBag.Title = "Groups";
    ViewBag.Name = "Groups";
}


@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/jquery.dataTables_themeroller.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
}
@Html.Action("_Breadcrumb", "CSVUpload", new { name = ViewBag.Name })
@if (Model == null)
{
    Html.RenderPartial("_UploadForm");
}
@if (Model != null)
{
    <div class="panel panel-info">
        <span class="red">You successfully added @ViewBag.numberOfCorrectRecords new record(s) to the @ViewBag.Name table. @ViewBag.numberOfDuplicateRecords record(s) were duplicates.</span>
    </div>
    if (Model.Count() > 0)
    {
        <div class="display" id="DBTable">
            <h4>List of rejected  @ViewBag.Name please review and re-upload</h4>
            @{Html.RenderPartial("_DataBaseTable", Model);}
        </div>
    }
}
@section scripts
{
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/DataTables-1.9.4/extras/TableTools/media/js/TableTools.min.js"></script>
    <script src="~/Scripts/custom/ViewDataHelper.js"></script>
}

HydroServerTools/Views/CSVUpload/ISOMetadata.cshtml
@model IEnumerable<HydroserverToolsBusinessObjects.Models.ISOMetadataModel>
@{
    ViewBag.Title = "ISOMetadata";
    ViewBag.Name = "ISOMetadata";
}


@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/jquery.dataTables_themeroller.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
}
@Html.Action("_Breadcrumb", "CSVUpload", new { name = ViewBag.Name })
@if (Model == null)
{
    Html.RenderPartial("_UploadForm");
}
@if (Model != null)
{
    <div class="panel panel-info">
        <span class="red">You successfully added @ViewBag.numberOfCorrectRecords new record(s) to the @ViewBag.Name table. @ViewBag.numberOfDuplicateRecords record(s) were duplicates.</span>
    </div>
    if (Model.Count() > 0)
    {
        <div class="display" id="DBTable">
            <h4>List of rejected  @ViewBag.Name please review and re-upload</h4>
            @{Html.RenderPartial("_DataBaseTable", Model);}
        </div>
    }
}
@section scripts
{
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/DataTables-1.9.4/extras/TableTools/media/js/TableTools.min.js"></script>
    <script src="~/Scripts/custom/ViewDataHelper.js"></script>
}

HydroServerTools/Views/CSVUpload/Index.cshtml
@model HydroServerTools.Models.ConnectionModel
@{
    ViewBag.Title = "VerticalTab";
}
@section styles{
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />

    <link href="~/Content/DataTables-1.9.4/media/css/demo_table.css" rel="stylesheet" />

}
<h1>Please set up connection</h1>
<div>

    @using (Html.BeginForm("TestConnection", "CSVUpload", new { @class = "form-horizontal" }))
    {

        <div class="control-group">
            @Html.LabelFor(m => m.ServerName, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(m => m.ServerName, new { @value = "mseul-cuahsi" })
                @Html.ValidationMessageFor(m => m.ServerName, null, new { @class = "help-inline" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.DataSourceName, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(m => m.DataSourceName, new { @value = "LittleBear_1_1_1" })
                @Html.ValidationMessageFor(m => m.DataSourceName, null, new { @class = "help-inline" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.Username, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(m => m.Username, new { @value = "martin" })
                @Html.ValidationMessageFor(m => m.Username, null, new { @class = "help-inline" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.Password, new { @class = "control-label" })
            <div class="controls">
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Test Connection</button>
            <a href="/CSVUpload/Upload" class="btn btn-default active" role="button">Link</a>

        </div>



        @*@Html.ValidationSummary(true)
            <div class="row">
                <fieldset>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.ServerName);

                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ServerName, new { @Value = "mseul-cuahsi", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ServerName)


                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.DataSourceName);
                    </div> <div class="editor-field">
                        @Html.TextBoxFor(model => model.DataSourceName, new { @Value = "LittleBear_1_1_1", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DataSourceName)
                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Username);
                    </div><div class="editor-field">
                        @Html.TextBoxFor(model => model.Username, new { @Value = "martin", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Username)
                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Password)
                    </div><div class="editor-field">
                        @Html.EditorFor(model => model.Password, new { @Value = "ms", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Password)
                    </div>


                </fieldset>
            </div>
                 <div class="row">
                    <input type="submit" class="btn btn-primary" value="connect" />
                </div>
        *@
        if (@Model != null)
        {

            if (@Model.Status != null)
            {
                if (Model.Message.ToString().Length > 0)
                {
                    if (@Model.Status.ToLower() == "success")
                    {

                        <p><div class="alert alert-success">@Model.Message;</div></p>

                    }
                    else
                    {
                        <p><div class="alert alert-danger">@Model.Message;</div></p>
                    }

                }
            }

        }
        @*if (@Model.Message != null)
            {
                @Model.Message;
            }*@
    }

</div>


@section scripts{
    <script src="~/Scripts/jquery-ui-1.10.3.js"></script>
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/UploadHelper.js"></script>
    <script>


    </script>

}

HydroServerTools/Views/CSVUpload/OffsetTypes.cshtml
@model IEnumerable<HydroserverToolsBusinessObjects.Models.OffsetTypesModel>
@{
    ViewBag.Title = "OffsetTypes";
    ViewBag.Name = "OffsetTypes";
}


@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/jquery.dataTables_themeroller.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
}
@Html.Action("_Breadcrumb", "CSVUpload", new { name = ViewBag.Name })
@if (Model == null)
{
    Html.RenderPartial("_UploadForm");
}
@if (Model != null)
{
    <div class="panel panel-info">
        <span class="red">You successfully added @ViewBag.numberOfCorrectRecords new record(s) to the @ViewBag.Name table. @ViewBag.numberOfDuplicateRecords record(s) were duplicates.</span>
    </div>
    if (Model.Count() > 0)
    {
        <div class="display" id="DBTable">
            <h4>List of rejected  @ViewBag.Name please review and re-upload</h4>
            @{Html.RenderPartial("_DataBaseTable", Model);}
        </div>
    }
}
@section scripts
{
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/DataTables-1.9.4/extras/TableTools/media/js/TableTools.min.js"></script>
    <script src="~/Scripts/custom/ViewDataHelper.js"></script>
}

HydroServerTools/Views/CSVUpload/_UploadForm.cshtml
<div class="jumbotron">
    <h2>Upload @ViewBag.Title</h2>

    @using (Html.BeginForm("Import", "CSVUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
        @Html.ValidationSummary(false)
        </div>
        <input type="hidden" name="viewname" value=@ViewBag.Name />
        <input type="file" class="btn btn-primary" name="file" required placeholder="Please select a csv file " />
        <input type="submit" class="btn btn-primary btn-info" value="Upload and Process" />
    }
</div>